name: MacroProject
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: Agfi-Hermawan
targets:
  MacroProject:
    type: application
    platform: iOS
    sources: [MacroProject]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: Agfi-Hermawan.MacroProject
      GENERATE_INFOPLIST_FILE: YES
  MacroProject-Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [MacroProject-Tests]
    dependencies:
      - target: MacroProject
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MacroProject.app/MacroProject"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES
schemes:
  MacroProject:
    build:
      targets:
        MacroProject: all
        MacroProject-Tests: all
    test:
      targets:
        - name: MacroProject-Tests
          gatherCoverageData: true
