name: MacroProject
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: Agfi-Hermawan
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    minorVersion: 2.5.1
targets:
  MacroProject:
    type: application
    platform: iOS
    sources: [MacroProject]  # Use a wildcard to include all source files
    resources: [Resources]    # Use a wildcard to include all resource files
    dependencies:
      - package: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: Agfi-Hermawan.MacroProject
        GENERATE_INFOPLIST_FILE: YES  # Ensure this is applied at the base level
      configurations:
        Debug:
          INFOPLIST_FILE: Info.plist  # Specify the Info.plist file if needed
        Release:
          INFOPLIST_FILE: Info.plist  # Specify the Info.plist file if needed
    buildPhases:
      - name: Link Frameworks
        type: frameworks
        files:
          - package: Supabase
          - package: Routing
schemes:
  MacroProject:
    build:
      targets:
        MacroProject: all
    test:
      targets: []
